export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_RECOMMENDED_SONGS_PENDING = 'FETCH_RECOMMENDED_SONGS_PENDING';
export const FETCH_RECOMMENDED_SONGS_SUCCESS = 'FETCH_RECOMMENDED_SONGS_SUCCESS';
export const FETCH_RECOMMENDED_SONGS_ERROR = 'FETCH_RECOMMENDED_SONGS_ERROR';
export const CREATE_PLAYLIST_PENDING = 'CREATE_PLAYLIST_PENDING';
export const CREATE_PLAYLIST_SUCCESS = 'CREATE_PLAYLIST_SUCCESS';
export const CREATE_PLAYLIST_ERROR = 'CREATE_PLAYLIST_ERROR';
