export const FETCH_CURRENT_USER = 'FETCH_CURRENT_USER';
export const FETCH_RECOMMENDED_SONGS_PENDING = 'FETCH_RECOMMENDED_SONGS_PENDING';
export const FETCH_RECOMMENDED_SONGS_SUCCESS = 'FETCH_RECOMMENDED_SONGS_SUCCESS';
export const FETCH_RECOMMENDED_SONGS_ERROR = 'FETCH_RECOMMENDED_SONGS_ERROR';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
